version: '3'

services:

  ########################################    非业务   ########################################

  #jaeger链路追踪
  jager_collector:
    image: jaegertracing/jaeger-collector:1.18
    container_name: jager_collector
    restart: always
    environment:
      - SPAN_STORAGE_TYPE=elasticsearch
      - ES_SERVER_URLS=http://elasticsearch:9200
      - ES_USERNAME=elastic
      - ES_PASSWORD=elasticseven666
      - LOG_LEVEL=debug
    networks:
      - looklook_net
    ports:
      - "14269"
      - "14268:14268"
      - "14267"
      - "14250:14250"
      - "9411:9411"

  jager_agent:
    image: jaegertracing/jaeger-agent:1.18
    container_name: jager_agent
    restart: always
    environment:
      - REPORTER_GRPC_HOST_PORT=jager_collector:14250
      - LOG_LEVEL=debug
    ports:
      - "5775:5775/udp"
      - "5778:5778"
      - "6831:6831/udp"
      - "6832:6832/udp"
    networks:
      - looklook_net
    depends_on:
      - jager_collector

  jaeger_query:
    image: jaegertracing/jaeger-query:1.18
    restart: always
    container_name: jaeger_query
    environment:
      - SPAN_STORAGE_TYPE=elasticsearch
      - ES_SERVER_URLS=http://elasticsearch:9200
      - ES_USERNAME=elastic
      - ES_PASSWORD=elasticseven666
      - LOG_LEVEL=debug
    ports:
      - 16686:16686
    networks:
      - looklook_net

  #prometheus监控
  prometheus:
    image: prom/prometheus:v2.28.1
    container_name: prometheus
    volumes:
      - ./data/prometheus/server/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./data/prometheus/data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
    restart: always
    user: root
    ports:
      - 9090:9090
    networks:
      - looklook_net

  #查看prometheus监控数据
  grafana:
        image: grafana/grafana:8.0.6
        container_name: grafana
        hostname: grafana
        restart: always
        volumes:
            - ./data/grafana/data:/var/lib/grafana
        ports:
            - "3001:3000"
        networks:
            - looklook_net

  #搜集kafka业务日志、存储prometheus监控数据
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.13.4
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    volumes:
      - ./data/elasticsearch/data:/usr/share/elasticsearch/data
    restart: always
    ports:
    - 9200:9200
    - 9300:9300
    networks:
      - looklook_net

  #查看elasticsearch数据
  kibana:
    image: docker.elastic.co/kibana/kibana:7.13.4
    container_name: kibana
    environment:
      - elasticsearch.hosts=http://elasticsearch:9200
    restart: always
    networks:
      - looklook_net
    depends_on:
      - "elasticsearch"
    ports:
      - "5601:5601"

  #收集业务数据
  filebeat:
    image: elastic/filebeat:7.13.4
    container_name: filebeat
    user: root
    restart: always
    volumes:
      - /var/lib/docker/containers:/var/lib/docker/containers
    networks:
      - looklook_net

  #kafka的服务注册发现
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    # always restart
    restart: always
    ports:
      - 2181:2181
    networks:
      - looklook_net

  #消息队列
  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    ports:
      - 9092:9092
    # host ip
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    # always restart
    restart: always
    volumes:
      - ./data/kafka/docker.sock:/var/run/docker.sock
    networks:
      - looklook_net


  ########################################    业务   ########################################

  #认证服务、颁发token
  identity-rpc:
    image: cosmtrek/air:latest
    container_name: identity-rpc
    environment:
      # 时区上海
      TZ: Asia/Shanghai
      GOPROXY: https://goproxy.cn,direct
    ports:
      - 9001:9001
    working_dir: /go/src/github.com/looklook/app/identity/cmd/rpc
    volumes:
      -  .:/go/src/github.com/looklook
    privileged: true
    restart: always
    networks:
      - looklook_net

  #认证服务api
  identity-api:
    image: cosmtrek/air:latest
    container_name: identity-api
    environment:
      # 时区上海
      TZ: Asia/Shanghai
      GOPROXY: https://goproxy.cn,direct
    ports:
      - 8001:8001
    working_dir: /go/src/github.com/looklook/app/identity/cmd/api
    volumes:
      -  .:/go/src/github.com/looklook
    privileged: true
    restart: always
    networks:
      - looklook_net
    depends_on:
      - identity-rpc

  #用户服务grpc
  usercenter-rpc:
    image: cosmtrek/air:latest
    container_name: usercenter-rpc
    environment:
      # 时区上海
      TZ: Asia/Shanghai
      GOPROXY: https://goproxy.cn,direct
    ports:
      - 9002:9002
    working_dir: /go/src/github.com/looklook/app/usercenter/cmd/rpc
    volumes:
      -  .:/go/src/github.com/looklook
    privileged: true
    restart: always
    networks:
      - looklook_net
    depends_on:
      - identity-rpc

  #用户服务api
  usercenter-api:
    image: cosmtrek/air:latest
    container_name: usercenter-api
    environment:
      # 时区上海
      TZ: Asia/Shanghai
      GOPROXY: https://goproxy.cn,direct
    ports:
      - 8002:8002
    working_dir: /go/src/github.com/looklook/app/usercenter/cmd/api
    volumes:
      -  .:/go/src/github.com/looklook
    privileged: true
    restart: always
    networks:
      - looklook_net
    depends_on:
      - usercenter-rpc
      - identity-rpc

  #旅行服务rpc
  travel-rpc:
    image: cosmtrek/air:latest
    container_name: travel-rpc
    environment:
      # 时区上海
      TZ: Asia/Shanghai
      GOPROXY: https://goproxy.cn,direct
    ports:
      - 9003:9003
    working_dir: /go/src/github.com/looklook/app/travel/cmd/rpc
    volumes:
      -  .:/go/src/github.com/looklook
    privileged: true
    restart: always
    networks:
      - looklook_net

  #旅行服务api
  travel-api:
    image: cosmtrek/air:latest
    container_name: travel-api
    environment:
      # 时区上海
      TZ: Asia/Shanghai
      GOPROXY: https://goproxy.cn,direct
    ports:
      - 8003:8003
    working_dir: /go/src/github.com/looklook/app/travel/cmd/api
    volumes:
      -  .:/go/src/github.com/looklook
    privileged: true
    restart: always
    networks:
      - looklook_net
    depends_on:
      - usercenter-rpc
      - order-rpc
      - travel-rpc

  #订单服务rpc
  order-rpc:
    image: cosmtrek/air:latest
    container_name: order-rpc
    environment:
      # 时区上海
      TZ: Asia/Shanghai
      GOPROXY: https://goproxy.cn,direct
    ports:
      - 9004:9004
    working_dir: /go/src/github.com/looklook/app/order/cmd/rpc
    volumes:
      -  .:/go/src/github.com/looklook
    privileged: true
    restart: always
    networks:
      - looklook_net
    depends_on:
      - travel-rpc
      - mqueue-rpc

  #订单服务api
  order-api:
    image: cosmtrek/air:latest
    container_name: order-api
    environment:
      # 时区上海
      TZ: Asia/Shanghai
      GOPROXY: https://goproxy.cn,direct
    ports:
      - 8004:8004
      - 8491:9091
    working_dir: /go/src/github.com/looklook/app/order/cmd/api
    volumes:
      -  .:/go/src/github.com/looklook
    privileged: true
    restart: always
    networks:
      - looklook_net
    depends_on:
      - payment-rpc
      - order-rpc

  #订单服务消息队列、延迟队列
  order-mq:
    image: cosmtrek/air:latest
    container_name: order-mq
    environment:
      # 时区上海
      TZ: Asia/Shanghai
      GOPROXY: https://goproxy.cn,direct
    ports:
      - 7004:7004
    working_dir: /go/src/github.com/looklook/app/order/cmd/mq
    volumes:
      -  .:/go/src/github.com/looklook
    privileged: true
    restart: always
    networks:
      - looklook_net
    depends_on:
      - usercenter-rpc
      - order-rpc
      - mqueue-rpc

  #支付服务rpc
  payment-rpc:
    image: cosmtrek/air:latest
    container_name: payment-rpc
    environment:
      # 时区上海
      TZ: Asia/Shanghai
      GOPROXY: https://goproxy.cn,direct
    ports:
      - 9005:9005
    working_dir: /go/src/github.com/looklook/app/payment/cmd/rpc
    volumes:
      - .:/go/src/github.com/looklook
    privileged: true
    restart: always
    networks:
      - looklook_net
    depends_on:
      - mqueue-rpc

  #支付服务api
  payment-api:
    image: cosmtrek/air:latest
    container_name: payment-api
    environment:
      # 时区上海
      TZ: Asia/Shanghai
      GOPROXY: https://goproxy.cn,direct
    ports:
      - 8005:8005
    working_dir: /go/src/github.com/looklook/app/payment/cmd/api
    volumes:
      -  .:/go/src/github.com/looklook
    privileged: true
    restart: always
    networks:
      - looklook_net
    depends_on:
      - payment-rpc
      - usercenter-rpc
      - order-rpc

  #内部消息队列、延迟消息队列
  mqueue-rpc:
    image: cosmtrek/air:latest
    container_name: mqueue-rpc
    environment:
      # 时区上海
      TZ: Asia/Shanghai
      GOPROXY: https://goproxy.cn,direct
    ports:
      - 9006:9006
    working_dir: /go/src/github.com/looklook/app/mqueue/cmd/rpc
    volumes:
      -  .:/go/src/github.com/looklook
    privileged: true
    restart: always
    networks:
      - looklook_net

  #内部消息服务(发送手机、邮件、微信模版消息)
  message-mq:
    image: cosmtrek/air:latest
    container_name: message-mq
    environment:
      # 时区上海
      TZ: Asia/Shanghai
      GOPROXY: https://goproxy.cn,direct
    ports:
      - 7007:7007
    working_dir: /go/src/github.com/looklook/app/message/cmd/mq
    volumes:
      -  .:/go/src/github.com/looklook
    privileged: true
    restart: always
    networks:
      - looklook_net


networks:
  looklook_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16

